[alias]
# 📦 Build & Check
b = "build"
chk-al = "check --all-targets --all-features"
chk = "check"

# 🧹 Format & Lint
pp = "fmt --all"
f = "fmt --all"
lint = "clippy --all-targets --all-features -- -D warnings"
c = "clippy --all-targets --all-features -- -D warnings"

# 🧪 Testing

t-al = "test"
t = "test --lib"
t-d = "test --doc"
t-r = "test --all-targets --all-features --release"

# 📚 Documentation
d = "doc --no-deps"
d-opn = "doc --no-deps --open"

# 🚀 Release
release = "build --release"
r = "run --release"
